### ISSUE TITLE
GeographicPosition is obsolete in GeoJSON.Net

### ISSUE THREAD

**Issue by inzanenl** [GeoJSON-Net/GeoJSON.Net.Contrib#12]
See changeset https://github.com/GeoJSON-Net/GeoJSON.Net/commit/81080d3fdb7b7ef9ce2a6f9af9af7d278e860473

GeographicPosition needs to be replaced with Position.

**Comment by xfischer** [comment]
OK thanks @inzanenl. Will fit that within the next hours.

**Comment by xfischer** [comment]
OK. Nuget package published.
@inzanenl Can you test if it is OK, and close if it is ?
Thanks

**Comment by inzanenl** [comment]
Seems OK now! I'm closing this issue.
