### ISSUE TITLE
Cannot load GeoJSON.NetContrib.Wkbconversions

### ISSUE THREAD

**Issue by kennethhaspeel** [GeoJSON-Net/GeoJSON.Net.Contrib#16]
I was experimenting with WKB conversions but .ToWkb() gave me an error
`{"Kan bestand of assembly GeoJSON.NetContrib.WkbConversions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.":"GeoJSON.NetContrib.WkbConversions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"}`

It's in Dutch but I assume the message is clear. GeoJSON.NetContrib.WkbConversions could not be found

**Comment by xfischer** [comment]
HI @kennethhaspeel, the problem is identified. I have released to quickly the NuGets.
Check out versions 0.1.1 recently updated on NuGet.
Now EF package references Wkb NuGet.

**Comment by kennethhaspeel** [comment]
Thanks for the (extremly) fast reply and solution. Problem solved
