### ISSUE TITLE
Support for NETStandard

### ISSUE THREAD

**Issue by xplicit** [GeoJSON-Net/GeoJSON.Net.Contrib#20]
Current version of library does not support NETStandard. Is it possible to make it compatible with NETStandard 2.0?

**Comment by xfischer** [comment]
Hi @xplicit. Which library are you focused at ? (There are 3 here)

**Comment by xplicit** [comment]
I'm trying to convert WKT to GeoJson and looks like `GeoJSON.Net.Contrib.MsSqlSpatial` should do this stuff. But it is targeted to .NET 4.5 only without supporting NETStandard in csproj file.

**Comment by alvaromongon** [comment]
Hi @xplicit, feel free to try to target netstandad and launch a PR, but I am not sure if all the necessary libraries will be available in standard. 

In the worst case scenario you could target a newer version of de full framework, like 4.6.1 that is compatible with standard 2.0

**Comment by trevor-thoele** [comment]
I created https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/pull/28. This does not impact MsSqlSpatial. Is it desired for me to do anything with it, such as the above target of framework 4.6.1?

**Comment by xfischer** [comment]
If it targets net45; it is compatible with netstandard20. I don't get why you need explicit netstandard20 targeting ?

**Comment by trevor-thoele** [comment]
Pulling in the package as it is into a .netcore 3.1 project causes warnings to be issued; I don't believe this is results in any errors. Placing the library onto .netstandard should eliminate these warnings.

**Comment by xfischer** [comment]
@trevor-thoele ah yes you are right. This is causing suspicion of runtime errors.
