### ISSUE TITLE
.NET 5?

### ISSUE THREAD

**Issue by jdege** [GeoJSON-Net/GeoJSON.Net.Contrib#35]
We'd been using GeoJSON.Net.Contrib.MsSqlSpatial in a few .NET Framework 4.5 projects, without issue.

Now we're trying to move to .NET 5, and we are having issues.

The most recent package we can find on .NuGet is 0.3.6, from July 2, 2020. And it has a dependency on .NETFramework v4.5.

Has anyone built an equivalent package that does support .NET 5?

**Comment by xfischer** [comment]
Hi, thanks for reporting this.

Anyone I know ? No. Anyone Google knows ? Maybe.

Can you describe the errors you're getting ?

Will try on my part to reproduce.

**Comment by jdege** [comment]
Create a new .NET 5.0 console application.

Install GeoJSON.Net (v1.2.19) and GeoJSON.Net.Contrib.MsSqlSpatial (v.0.3.6)

If I do a build, I get  warning: 

warning NU1701: Package 'GeoJSON.Net.Contrib.MsSqlSpatial 0.3.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

**Comment by xfischer** [comment]
OK, but does it run ?

**Comment by xfischer** [comment]
OK I've found a fix : 

1. In your csproj file, add the following lines : 

```xml  
<ItemGroup>
    <!-- inspired by https://github.com/dotnet/SqlClient/issues/30#issuecomment-460504614 -->
    <None Include="$(USERPROFILE)/.nuget/packages/microsoft.sqlserver.types/14.0.1016.290/nativeBinaries/**" CopyToOutputDirectory="PreserveNewest" Link="SqlServerTypes/%(RecursiveDir)%(Filename)%(Extension)" Visible="false" />
  </ItemGroup>
```

2. Add a NuGet package reference to System.Data.SqlClient
3. In your main program, add an assembly loader method : 
```csharp
 public static void AssemblyInit()
        {
            var basePath = Path.Combine(
                Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().CodeBase).AbsolutePath) ?? Environment.CurrentDirectory,
                "SqlServerTypes",
                Environment.Is64BitProcess ? "x64" : "x86");

            void LoadLibrary(string libraryFilename)
            {
                var libraryPath = Path.Combine(basePath, libraryFilename);
                var libraryAddress = NativeMethods.LoadLibrary(libraryPath);
                if (libraryAddress == IntPtr.Zero)
                {
                    throw new Win32Exception($"Failed to load SQL Server DLL \"{libraryPath}\".");
                }
            }

            LoadLibrary("msvcr120.dll");
            LoadLibrary("SqlServerSpatial140.dll");
        }

        private static class NativeMethods
        {
            [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
            public static extern IntPtr LoadLibrary(string libraryName);
        }
```
3. In your Main Program, add a call to `AssemblyInit();` 

See full main.cs code here : https://gist.github.com/xfischer/74d0498b83a447e464ae617ac0ca2e79

**Comment by jdege** [comment]
I'll give that a try

**Comment by jdege** [comment]
What you've provided seems to be a method for loading a couple of dependent DLLs, at runtime.

I'm not getting that far. I am still unable to install the GeoJson.NET.Contrib.MsSqlSpatial NuGet package.

`NU1701	Package 'GeoJSON.Net.Contrib.MsSqlSpatial 0.3.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

**Comment by xfischer** [comment]
It's a warning, not an error. The package should be installed.
Warning says "you may run into problems is something coded in the package is not net5 compliant". Which is not the case, so go ahead for that part.

**Comment by jdege** [comment]
I'm afraid it's not just a warning.

I'm getting two errors - the other is:

`Package restore failed. Rolling back package changes for 'xx_shared'.				`

A web search suggested that I clear my NuGet cache.  That made no difference.

**Comment by xfischer** [comment]
I have setup a simple NET5 projet and did not have any issues : please test here : https://www.dropbox.com/t/uHeD1QwqgikpQi50

**Comment by jdege** [comment]
Unfortunately, our projects are anything but simple.

I removed all of the NuGet packages from a project, then tried to add GeoJSON.NET v1.2.19 and GeoJSON.NET.Contrib.MsSqlSpatial v.0.3.6, and still saw the same problem.

But when I add them to a new, clean project, I have no issues.

Which makes it my problem, not yours.

But... it looks like your loading Windows DLLs, and that won't work for us.

The reason we're moving to .NET 5.0 is to be able to run on Linux, in vanilla Docker containers, etc. Adding runtime dependencies to Windows DLLs is not acceptable.

Which gets me back to the original question - we need to be able to do spatial comparisons within EF LINQ queries, and we've been doing that with your package.

Is there an alternative approach?

Could we use WKB?

**Comment by xfischer** [comment]
Yes, there are plenty of other alternatives. The weapon of choice would be NetTopologySuite in your case (see : https://docs.microsoft.com/fr-fr/ef/core/modeling/spatial)

Do you use GeoJSON at all ?

**Comment by jdege** [comment]
We're using both GeoJSON.NET and NetTopologySuite, and routinely converting from one to the other and back.

For reasons I don't entirely understand. It looks like we're doing most of our work in the NetTopologySuite classes, and then converting to and from the GeoJSON.NET classes for IO, and for comparisons in EF queries.

What we return to the Browser, for example, is always GeoJSON - and is created using GeoJSON.NET classes.  But all of the processing on geometries - unions, intersections, etc. - is done using NetTopologySuite classes.

It may make more sense to use NetTopologySuite, and it's NetTopologySuite.IO.GeoJson, and to not use GeoJSON.NET at all.

Particularly if NetTopologySuite integrates easily into EF.

Thank's for your time and advice.
