### ISSUE TITLE
Implementation in a docker  container.

### ISSUE THREAD

**Issue by rodriguesmvinicius** [GeoJSON-Net/GeoJSON.Net.Contrib#36]
Hello,

First of all, congrats for the solution. Is quite complete and well done!

I am trying to deploy my solution using the Net.Contrib into a docker/container environment and I am having a hard time with the SqlServer.Types.

It keeps hitting the " Unable to load shared library 'SqlServerSpatial140.dll' or one of its dependencies" error.

I have tried put the dll in the app folder, in the usr/bin folder. everywhere.

Have you guys faced a scenario like this? Could you share me some wisdom?

Thanks in advance.

**Comment by xfischer** [comment]
Hi @rodriguesmvinicius, yes it's sometimes a headache.

Did you try, in your top level program, to run the following code ?

`SqlServerTypes.Utilities.LoadNativeAssemblies(AppDomain.CurrentDomain.BaseDirectory);`

*AppDomain.CurrentDomain.BaseDirectory* can be any directory where the sql bits files resides.

![image](https://user-images.githubusercontent.com/2776898/125210225-aa038680-e29e-11eb-8559-c8fee4d9bdd9.png)
