### ISSUE TITLE
Empty SqlGeography/Geometry MultiPolygon throws NotSupportedException

### ISSUE THREAD

**Issue by Sheepzez** [GeoJSON-Net/GeoJSON.Net.Contrib#6]
```
SqlGeographyBuilder builder = new SqlGeographyBuilder();
builder.SetSrid(4326);
builder.BeginGeography(OpenGisGeographyType.MultiPolygon);
builder.EndGeography();
geoJSON = builder.ConstructedGeography.ToGeoJSONGeometry();
```

Code above results in the following exception:
```
An exception of type 'System.NotSupportedException' occurred in GeoJSON.Net.Contrib.MsSqlSpatial.dll but was not handled in user code

Additional information: Geometry type MultiPolygon is not supported yet.
```

whereas the code below will work fine:

```
SqlGeographyBuilder builder = new SqlGeographyBuilder();
builder.SetSrid(4326);
builder.BeginGeography(OpenGisGeographyType.MultiPolygon);
builder.BeginGeography(OpenGisGeographyType.Polygon);
builder.EndGeography();
builder.EndGeography();
geoJSON = builder.ConstructedGeography.ToGeoJSONGeometry();
```

The same also seems to apply to SqlGeometries.

**Comment by xfischer** [comment]
Thanks for reporting @Sheepzez. I have reproduced the issue. Will fix it today.

**Comment by xfischer** [comment]
@Sheepzez  Harder than I thought... Correction : will fit it [as soon as possible].

**Comment by Sheepzez** [comment]
No problem, @xfischer. I've just been filling with the empty Polygon, which works fine for my application.

**Comment by Sheepzez** [comment]
@xfischer Noticed you committed a fix for this. Could you update the NuGet package to include this? Perhaps an automatic rebuild and package for NuGet would be useful?

**Comment by xfischer** [comment]
@Sheepzez I have no control on this repo, even if I'm the main contributor.
@jbattermann is in charge here. And I'm sure he'll get things done when he can. I you're stuck you can fork my own repo from where this PR originates : [xfischer/GeoJSON.Net.Contrib](https://github.com/xfischer/GeoJSON.Net.Contrib)

**Comment by jbattermann** [comment]
@Sheepzez / @xfischer I am here - just had a slightly busy week :)

@xfischer I saw the latest CI build yesterday for the pull request failed apparently because of a .Net version mismatch, see https://ci.appveyor.com/project/jbattermann/geojson-net-contrib/build/13-rmbgamhn particularly

```
The primary reference "GeoJSON.Net, Version=0.1.38.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" which was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
```

I was going to update GeoJSON to 4.5 & Json.Net 7.x .. would / could you do the same for the contrib one? Or are you forced staying on .Net 4.0?

**Comment by xfischer** [comment]
@jbattermann No restrictions for me. I was targeting the same as GeoJSON. Let's do it !

**Comment by jbattermann** [comment]
Alright perfect - I'll do it right away and let you know when 'core' is done.

Cheers!

**Comment by xfischer** [comment]
PR #7 updated with net45 and json 8.0.2. Is this OK for json version ?

**Comment by jbattermann** [comment]
Looks good :+1: 

Core is a Portable Class Library, soooo it'll take just a bit longer..

**Comment by jbattermann** [comment]
Alright - both packages are updated & published on nuget.org - contrib is 0.1.5: https://www.nuget.org/packages/GeoJSON.Net.Contrib.MsSqlSpatial \o/

Thanks @xfischer !

@Sheepzez let us know if this fixes your issue

**Comment by Sheepzez** [comment]
Hey @xfischer, and @jbattermann.
.ToGeoJsonGeometry() no longer throws an exception from that code. I do get the following exception when I try to use Newtonsoft's JsonConvert.SerializeObject() on the resulting IGeometryObject though. The full exception is:

```
An exception of type 'Newtonsoft.Json.JsonWriterException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Token PropertyName in state ArrayStart would result in an invalid JSON object. Path 'coordinates'.
```

The code generating the geojson is:

```
SqlGeographyBuilder builder = new SqlGeographyBuilder();
builder.SetSrid(4326);
builder.BeginGeography(OpenGisGeographyType.MultiPolygon);
builder.EndGeography();
geoJSON = builder.ConstructedGeography.ToGeoJSONGeometry();
```

**Comment by xfischer** [comment]
@jbattermann Hi, after investigating, it seems that in MultiPolygonConverter.WriteJson(...) the last call to  writer.WriteEndArray() should be after the closing bracket ;)

**Comment by jbattermann** [comment]
Good catch @xfischer - [update built/pushed](https://www.nuget.org/packages/GeoJSON.Net/0.1.45)!

**Comment by Sheepzez** [comment]
@xfischer @jbattermann Everything is working! Thanks for the quick fixes guys.

**Comment by jbattermann** [comment]
:+1:
