### ISSUE TITLE
Switch Lat Lon 

### ISSUE THREAD

**Issue by develtos** [GeoJSON-Net/GeoJSON.Net.Contrib#8]
Hi guys!

I have a problem with conversion from **SqlGeography** to **IGeometryObject** (use method - `MsSqlSpatialConvert.ToGeoJSONGeometry`). 
At the entrance I submit **Longitude**, **Latitude**, and the output is a sequence contrary **Latitude**, **Longitude**.

May be bug at line 63,70  _SqlGeographyGeoJSONSink.cs_  ?

Thanks.

**Comment by xfischer** [comment]
Thanks for reporting the issue @develtos !
There was effectively a misorder in lat/lon parameters. This is now fixed. 
@jbattermann could you push to nuget ?

**Comment by jbattermann** [comment]
@xfischer built & published! :+1:

**Comment by develtos** [comment]
thnx
