### ISSUE TITLE
Newtonsoft.Json Dependency should match GeoJSON.Net

### ISSUE THREAD

**Issue by jtroe** [GeoJSON-Net/GeoJSON.Net.Contrib#9]
Are you using an API that isn't available in v7.x?  This inconsistent versioning is causing issues in a large project where I'm using this.

If it was an oversight, I'd be happy to submit a PR.

Thanks!

**Comment by jbattermann** [comment]
Hi @jtroe / Jason, I am pretty sure this was just an oversight / mis-alignment because we went back and forth at one point a couple months back with the Json.Net version used - so yeah, a PR would be fine.. great actually!

**Comment by jbattermann** [comment]
Package with your PR has been published - thanks again Jason!
